ANALYZE sqlite_master;
INSERT INTO sqlite_stat1 VALUES('tracks','IFK_TrackMediaTypeId','3503 701');
INSERT INTO sqlite_stat1 VALUES('tracks','IFK_TrackGenreId','3503 141');
INSERT INTO sqlite_stat1 VALUES('tracks','IFK_TrackAlbumId','3503 11');
INSERT INTO sqlite_stat1 VALUES('playlist_track','IFK_PlaylistTrackTrackId','8715 3');
INSERT INTO sqlite_stat1 VALUES('playlist_track','sqlite_autoindex_playlist_track_1','8715 623 1');
INSERT INTO sqlite_stat1 VALUES('albums','IFK_AlbumArtistId','347 2');
INSERT INTO sqlite_stat1 VALUES('artists',NULL,'275');
INSERT INTO sqlite_stat1 VALUES('customers','IFK_CustomerSupportRepId','59 20');
INSERT INTO sqlite_stat1 VALUES('playlists',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('employees','IFK_EmployeeReportsTo','8 2');
INSERT INTO sqlite_stat1 VALUES('genres',NULL,'25');
INSERT INTO sqlite_stat1 VALUES('invoices','IFK_InvoiceCustomerId','412 7');
INSERT INTO sqlite_stat1 VALUES('media_types',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('invoice_items','IFK_InvoiceLineTrackId','2240 2');
INSERT INTO sqlite_stat1 VALUES('invoice_items','IFK_InvoiceLineInvoiceId','2240 6');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('genres',25);
INSERT INTO sqlite_sequence VALUES('media_types',5);
INSERT INTO sqlite_sequence VALUES('artists',275);
INSERT INTO sqlite_sequence VALUES('albums',347);
INSERT INTO sqlite_sequence VALUES('tracks',3503);
INSERT INTO sqlite_sequence VALUES('employees',8);
INSERT INTO sqlite_sequence VALUES('customers',59);
INSERT INTO sqlite_sequence VALUES('invoices',412);
INSERT INTO sqlite_sequence VALUES('invoice_items',2240);
INSERT INTO sqlite_sequence VALUES('playlists',18);
CREATE INDEX [IFK_AlbumArtistId] ON "albums" ([ArtistId]);
CREATE INDEX [IFK_CustomerSupportRepId] ON "customers" ([SupportRepId]);
CREATE INDEX [IFK_EmployeeReportsTo] ON "employees" ([ReportsTo]);
CREATE INDEX [IFK_InvoiceCustomerId] ON "invoices" ([CustomerId]);
CREATE INDEX [IFK_InvoiceLineInvoiceId] ON "invoice_items" ([InvoiceId]);
CREATE INDEX [IFK_InvoiceLineTrackId] ON "invoice_items" ([TrackId]);
CREATE INDEX [IFK_PlaylistTrackTrackId] ON "playlist_track" ([TrackId]);
CREATE INDEX [IFK_TrackAlbumId] ON "tracks" ([AlbumId]);
CREATE INDEX [IFK_TrackGenreId] ON "tracks" ([GenreId]);
CREATE INDEX [IFK_TrackMediaTypeId] ON "tracks" ([MediaTypeId]);

